pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - or:
        - base=main
        - base=edge
      - approved-reviews-by=SK1Y101
      - label!=work-in-progress
      - -closed
      - -merged
      - check-success=run_nox
      - check-success=update_release_draft
      - check-success=CodeFactor
      - check-success~=^security/snyk
    actions:
      assign:
        users: [SK1Y101]
      merge:
        method: merge

  - name: Create edge patches
    conditions:
      - base=main
    actions:
      backport:
        regexes: [edge]

  - name: Approve edge patches
    conditions:
      - base=edge
      - head=main
      - -closed
      - -merged
    actions:
      review:
        type: APPROVE

  - name: automatic merge for Allcontributors bot pull requests
    conditions:
      - base=main
      - author~=^allcontributors\[bot\]$
    actions:
      review:
        type: APPROVE

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE

  - name: automatic approve for My pull requests
    conditions:
      - author=SK1Y101
    actions:
      review:
        type: APPROVE

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
