pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - label!=work-in-progress
      - -closed
      - -merged
      - check-success=run_nox
      - check-success=update_release_draft
      - check-success=CodeFactor
      - check-success~=^security/snyk
    actions:
      assign:
        users: [SK1Y101]
      merge:
        method: merge

<<<<<<< HEAD
  - name: apply patches to the edge branch
=======
  - name: Create edge patches
    conditions:
      - base=main
    actions:
      backport:
        regexes: [edge]

  - name: Merge edge patches
>>>>>>> 80c9712 (ci(Mergify): configuration update)
    conditions:
      - base=main
    actions:
<<<<<<< HEAD
      backport:
        regexes: [edge]
=======
      merge:
        method: merge
>>>>>>> 80c9712 (ci(Mergify): configuration update)

  - name: automatic merge for Allcontributors bot pull requests
    conditions:
      - base=main
      - author~=^allcontributors\[bot\]$
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: automatic merge for My pull requests
    conditions:
      - author=SK1Y101
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
