pull_request_rules:
  - name: Merge to main when checks succeed
    conditions:
      - base=main
      - approved-reviews-by=SK1Y101
      - label!=work-in-progress
      - -closed
      - -merged
      - check-success=run_nox
      - check-success=update_release_draft
      - check-success=CodeFactor
      - check-success~=^security/snyk
    actions:
      assign:
        users: [SK1Y101]
      merge:
        method: merge

  - name: Create edge patches
    conditions:
      - base=main
    actions:
      backport:
        regexes: [edge]

  - name: Merge edge patches
    conditions:
      - base=main
      - head=edge
    actions:
      merge:
        method: merge

  - name: Add Contributors automatically
    conditions:
      - base=main
      - author~=^allcontributors\[bot\]$
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: Add dependencies automatically
    conditions:
      - author=dependabot[bot]
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: Approve my pull requests automatically
    conditions:
      - author=SK1Y101
    actions:
      review:
        type: APPROVE
      merge:
        method: merge

  - name: Remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
