# This workflow will install dependencies (including nox), using those to lint and run tests
name: Nox
on:
  push:
    branches: [ "main", "edge" ]
  pull_request:
    branches: [ "main", "edge" ]
permissions:
  contents: read
jobs:
  analyse-versions:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      buildnum: ${{ steps.build.outputs.buildnum }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0
    - name: Get build number
      id: build
      run: |
        echo "::set-output name=buildnum::$(git rev-list --count HEAD)"
  run_nox:
    runs-on: ubuntu-latest
    needs: analyse-versions
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint
      run: |
        nox -e lint -- --last_ver ${{ needs.analyse-tags.outputs.previous-tag }}
    - name: Type Checking
      run: |
        nox -e mypy
    - name: Test Suite
      run: |
        nox -e tests