# This workflow will install dependencies (including nox), using those to lint and run tests
name: Nox
on:
  push:
    branches: [ "main", "edge" ]
  pull_request:
    branches: [ "main", "edge" ]
permissions:
  contents: read
jobs:
  run_nox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        fetch-depth: 0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update tags in repo
      run: |
        git fetch --tags origin
    - name: Fetch build count (PR)
      run: |
        if [ ${{ github.event_name }} == 'pull_request' ]; echo $(git rev-list v0.0.0..${{ github.event.pull_request.head.sha }} --count); else echo $(git rev-list v0.0.0..${GITHUB_SHA} --count); fi
    - name: Get previous version
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.0.0
    - name: Lint
      run: |
        nox -e lint -- --last-ver ${{ steps.previoustag.outputs.tag }}
    - name: Type Checking
      run: |
        nox -e mypy
    - name: Test Suite
      run: |
        nox -e tests
